# -*- coding: utf-8 -*-
"""Global AI HUb Projesi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17n0JsQv3-htuAeVoQAV4JqHKvd0FEa77
"""

#Taş Kağı Makas Oyunu Projesi(Global AI Hub)



import random

class FantasyGame:
    def __init__(self):
        self.choices = ["dragon", "wizard", "knight", "elf", "troll"]
        self.rules = {
            "dragon": ["knight", "elf"],
            "wizard": ["dragon", "troll"],
            "knight": ["wizard", "elf"],
            "elf": ["dragon", "troll"],
            "troll": ["wizard", "knight"]
        }

#Taş kağı makas oyununa yeni bir soluk getirdim,karakter sayısı ve cinsini degiştirdim

    def get_user_choice(self):
        while True:
            user_input = input("Enter dragon, wizard, knight, elf, or troll: ").lower()
            if user_input in self.choices:
                return user_input
            print("Invalid input. Please enter dragon, wizard, knight, elf, or troll.")

    def get_computer_choice(self):
        return random.choice(self.choices)

    def determine_winner(self, user_choice, opponent_choice):
        if user_choice == opponent_choice:
            return "tie"
        elif opponent_choice in self.rules[user_choice]:
            return "win"
        else:
            return "lose"

    def play_set(self):
        user_choice = self.get_user_choice()
        opponent_choice = self.get_computer_choice()

        print(f"Opponent chose: {opponent_choice}")
        result = self.determine_winner(user_choice, opponent_choice)

        if result == "tie":
            print("This set is a tie!")
        elif result == "win":
            print("You won this set!")
        else:
            print("You lost this set!")

        return result

    def play_best_of_seven(self):
        user_wins = 0
        opponent_wins = 0

        while user_wins < 3 and opponent_wins < 3:
            result = self.play_set()
            if result == "win":
                user_wins += 1
            elif result == "lose":
                opponent_wins += 1

            print(f"Score - You: {user_wins}, Opponent: {opponent_wins}")

        if user_wins == 3:
            print("Congratulations! You won the match!")
        else:
            print("You lost the match.")

    def play_offline(self):
        print("Starting offline game...")
        self.play_best_of_seven()
#online seçeneği de tasarladım lakin süre aşımına uğrama sorunu başgösterdi,bu sorunu çözemedim.Oyunum offline bir oyun halini aldı.


def main():
    game = FantasyGame()
    mode = input("Enter 'offline' for offline mode: ").strip().lower()
    if mode == 'offline':
        game.play_offline()
    else:
        print("Invalid mode selected.")

if __name__ == "__main__":
    main()
#Hayli eğlenceli ve uzun soluklu bir oyun oldu.Ayrıca fantastik avatarlar birçok kişinin ilgisini çekmeye müsait.